### ISSUE TITLE
Many functions that use clipboard: Environment errors

### ISSUE THREAD

**Issue by mrflory** [pyro-team/bkt-toolbox#3]
When using a functions that makes use of copy-paste operations a lot, sometimes Environment error related to clipboard issues appear. For example when using "text onto shape" function for many shapes at once. This is reproducable within a PowerPoint instance.

Maybe make more use of `save_paste` function in `helpers.py`?

**Comment by mrflory** [comment]
Might also be related to comrelease:

```
Traceback (most recent call last):
  File "C:\xx\bkt-framework\bkt\addin.py", line 252, in _callback
    return_value= self.context.invoke_callback(callback, *args, **kwargs)
  File "C:\xx\bkt-framework\bkt\context.py", line 209, in invoke_callback
    return_value = self.app_callbacks.invoke_callback(self, callback, *args, **kwargs)
  File "C:\xx\bkt-framework\bkt\apps.py", line 232, in invoke_callback
    return_value = callback.method(**kwargs)
  File "C:\xx\bkt-framework\features\toolbox\text.py", line 1203, in textOutOfShape
    shp.TextFrame2.TextRange.Copy()
  File "C:\xx\bkt-framework\bkt\library\comrelease.py", line 317, in __call__
    return_value = getattr(self._auto_release_comobj._comobj, self._method)(*args_converted, **kwargs_converted)
EnvironmentError: System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard fehlgeschlagen (Ausnahme von HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
```

**Comment by mrflory** [comment]
Same issue in BKT Legacy > No Comrelease issue.
`save_paste` and a variation `save_copy` doesn't help.

I have attached a demo file to reproduce the problem with "text onto shape" function:
[bug_3.pptx](https://github.com/pyro-team/bkt-toolbox/files/7616261/bug_3.pptx)

**Comment by mrflory** [comment]
No further issues detected with clipboard. Will re-open if necessary.
